[dataset]
name = [ "s", "y", "m", "b", "o", "l", "s",]
init = [ "2", "0", "2", "2", "-", "1", "1", "-", "0", "6", "T", "1", "8", ":", "2", "3", ":", "1", "0",]
description = []
bucket = [ "f", "i", "n", "d", "a", "t", "a", "/", "y", "a", "h", "o", "o",]
path = [ "s", "y", "m", "b", "o", "l", "s",]

[current]
created = [ "2", "0", "2", "2", "-", "1", "1", "-", "0", "6", "T", "1", "8", ":", "2", "3", ":", "1", "0",]
format = [ "p", "a", "r", "q", "u", "e", "t",]
compression = [ "z", "s", "t", "d",]
partitioning = []
sort_by = []
ascending = true
distinct = false
columns = [ [ "s", "y", "m", "b", "o", "l",], [ "n", "a", "m", "e",], [ "e", "x", "c", "h", "a", "n", "g", "e",], [ "t", "y", "p", "e",], [ "i", "n", "d", "u", "s", "t", "r", "y",], [ "v", "a", "l", "i", "d",],]
batch_size = []
comment = [ "I", "n", "i", "t", "i", "a", "l", "i", "z", "e", "d",]

["snapshot.20221106_182315"]
creaded = [ "2", "0", "2", "2", "-", "1", "1", "-", "0", "6", "T", "1", "8", ":", "2", "3", ":", "1", "5",]
format = [ "p", "a", "r", "q", "u", "e", "t",]
compression = [ "z", "s", "t", "d",]
partitioning = []
sort_by = []
ascending = true
distinct = false
columns = [ [ "s", "y", "m", "b", "o", "l",], [ "n", "a", "m", "e",], [ "e", "x", "c", "h", "a", "n", "g", "e",], [ "t", "y", "p", "e",], [ "i", "n", "d", "u", "s", "t", "r", "y",], [ "v", "a", "l", "i", "d",],]
comment = []
